site_name: My Docs

# Theming and style
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  favicon: assets/favicon.png

# Navigation
nav:
  - Generals:
      - Project Generals: Generals/Project_generals.md
      - Overview & Problem Description: Generals/Overview_&_Problem_Description.md
      - Glossary & Domain Dictionary: Generals/Glossary_&_Domain_Dictionary.md
      - Stack Definition: Solution Tech/Proposed_Solution/Stack_definition.md
  - Solution:
      - Proposed Solution: Solution Tech/Proposed_Solution/Proposed_Solution.md
      - Data Model: Solution Tech/Proposed_Solution/Data_Model.md
      - Business Logic: Solution Tech/Proposed_Solution/Business_Logic.md
      - Presentation Layer: Solution Tech/Proposed_Solution/Presentation_Layer.md
      - Identity & Authentication Management: Solution Tech/IAM.md
      - Test Plan: Solution Tech/Test_Plan.md
